// <auto-generated />
using System;
using Carrinho.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carrinho.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarrinhoDbContext))]
    [Migration("20260919133909_CarrinhoCuponsCrud")]
    partial class CarrinhoCuponsCrud
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carrinho.Core.Entities.CarrinhoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoCupom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CupomId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentualDesconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CupomId");

                    b.ToTable("Carrinho", (string)null);
                });

            modelBuilder.Entity("Carrinho.Core.Entities.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoCupom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PercentualDesconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCupom")
                        .IsUnique();

                    b.ToTable("Cupom", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cupom_Percentual", "\"PercentualDesconto\" > 0 AND \"PercentualDesconto\" <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoCupom = "10OFF",
                            PercentualDesconto = 10m
                        },
                        new
                        {
                            Id = 2,
                            CodigoCupom = "15OFF",
                            PercentualDesconto = 15m
                        });
                });

            modelBuilder.Entity("Carrinho.Core.Entities.ItemCarrinho", b =>
                {
                    b.Property<Guid>("CarrinhoId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("CarrinhoId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemCarrinho", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItemCarrinho_Quantidade", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("Carrinho.Core.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Produto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produto_PrecoLiquido", "\"PrecoLiquido\" >= 0");

                            t.HasCheckConstraint("CK_Produto_QuantidadeEstoque", "\"QuantidadeEstoque\" >= 0");
                        });
                });

            modelBuilder.Entity("Carrinho.Core.Entities.CarrinhoCompra", b =>
                {
                    b.HasOne("Carrinho.Core.Entities.Cupom", null)
                        .WithMany()
                        .HasForeignKey("CupomId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Carrinho.Core.Entities.ItemCarrinho", b =>
                {
                    b.HasOne("Carrinho.Core.Entities.CarrinhoCompra", null)
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carrinho.Core.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Carrinho.Core.Entities.CarrinhoCompra", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
